-- ─────────────────────────────────────────────────────────────────────────────
-- BASELINE — kernschema SpeeQ
-- ─────────────────────────────────────────────────────────────────────────────
-- Waarom dit bestand bestaat: `projects`, `evidence`, `evidence_review`,
-- `presets`, `push_subscriptions`, `tenant_features` en `drawing_change_requests`
-- zijn ooit met de hand in het Supabase-dashboard aangemaakt, vóórdat er
-- migraties werden bijgehouden. Geen enkele migratie in deze map maakte ze aan.
-- Gevolg: de database was niet opnieuw op te bouwen en een nieuwe tenant-DB kon
-- niet betrouwbaar worden uitgerold.
--
-- Deze baseline is gereconstrueerd uit de productie-database (kgiuavfvhtdgwuygbyzo,
-- 25 juli 2026) en is de eerste migratie in de keten. Alle latere migraties in
-- deze map bouwen hierop voort.
--
-- Let op: de foreign keys van `evidence` en `drawing_change_requests` naar
-- `dossiers` en `floor_plans` staan bewust NIET hier — die tabellen worden pas
-- later in de keten aangemaakt. Zie 20260628_baseline_relaties.sql.

-- ── projects ────────────────────────────────────────────────────────────────
create table if not exists public.projects (
  id                               text primary key default (gen_random_uuid())::text,
  created_at                       timestamptz not null default now(),
  updated_at                       timestamptz not null default now(),
  name                             text,
  initiator_name                   text,
  address                          text,
  email                            text,
  kadastrale_aanduiding            text,
  latitude                         double precision,
  longitude                        double precision,
  owner_id                         uuid,
  kwaliteitsborger_id              uuid,
  instrument_id                    text,
  borgingsplan_url                 text,
  risicobeoordeling_url            text,
  dossier_bevoegd_gezag_url        text,
  verklaring_kwaliteitsborger_url  text,
  dso_bouwmelding_status           text,
  dso_meldings_datum               timestamptz,
  dso_transaction_id               text,
  dso_gereedmelding_status         text,
  dso_gereedmeldings_datum         timestamptz,
  dso_gereedmelding_transaction_id text,
  tenant_id                        text default 'demo'
);

-- ── evidence ────────────────────────────────────────────────────────────────
-- De kerntabel: één rij per vastgelegd controlepunt (foto + context + review).
create table if not exists public.evidence (
  id                          bigint generated by default as identity primary key,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),
  project_id                  text,
  inspection_point_id         text,
  photo_uri                   text,
  media_uri                   text,
  "timestamp"                 text,
  latitude                    double precision,
  longitude                   double precision,
  gps_accuracy                double precision,
  exif_hash                   text,
  exif_verified               boolean default false,
  user_id                     uuid,
  ifc_guid                    text,
  field_note                  text,
  sync_status                 text default 'PENDING',
  ai_status                   text default 'PENDING',
  ai_confidence               double precision,
  ai_notes                    text,
  cloud_record_id             bigint,
  kik_sync_status             text,
  bim_synced                  boolean default false,
  bim_topic_id                text,
  ocr_text                    text,
  betonkwaliteit              text,
  volume                      text,
  leverdatum                  text,
  milieuklasse                text,
  stop_moment_confirmed       boolean,
  measurement_tool_confirmed  boolean,
  location_verified           boolean,
  location_spoof_risk         text,
  location_security_message   text,
  discipline_id               text,
  dossier_scope               text,
  stop_moment_label           text,
  requires_measurement_tool   boolean default false,
  etage                       text,
  ruimtenummer                text,
  binnenbuiten                text default 'BINNEN',
  context_extra               jsonb default '{}'::jsonb,
  altitude                    double precision,
  altitude_accuracy           double precision,
  locatie_detail              text,
  floor_plan_id               uuid,
  pin_x                       real,
  pin_y                       real,
  sync_retry_count            integer not null default 0,
  sync_failed_reason          text,
  dossier_id                  uuid,
  is_locked                   boolean not null default false,
  tenant_id                   text default 'demo',
  review_status               text default 'PENDING_REVIEW'
    check (review_status in ('PENDING_REVIEW','APPROVED','REJECTED','FINALIZED')),
  reviewed_by                 uuid references auth.users(id),
  reviewed_at                 timestamptz,
  review_note                 text,
  client_uuid                 text,
  client_version              integer not null default 1,
  constraint evidence_project_id_fkey foreign key (project_id)
    references public.projects(id) on update cascade on delete restrict
);

-- ── evidence_review ─────────────────────────────────────────────────────────
create table if not exists public.evidence_review (
  id          bigint generated by default as identity primary key,
  evidence_id bigint references public.evidence(id) on delete cascade,
  reviewer_id uuid,
  status      text not null default 'PENDING',
  notes       text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  tenant_id   text default 'demo'
);

-- ── presets ─────────────────────────────────────────────────────────────────
create table if not exists public.presets (
  id         bigserial primary key,
  type       text not null check (type in ('project','inspection')),
  value      text not null,
  created_at timestamptz not null default now(),
  tenant_id  text default 'demo',
  constraint presets_type_value_uq unique (type, value)
);

-- ── push_subscriptions ──────────────────────────────────────────────────────
create table if not exists public.push_subscriptions (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  project_id   text,
  endpoint     text not null unique,
  keys_p256dh  text not null,
  keys_auth    text not null,
  device_label text,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ── tenant_features ─────────────────────────────────────────────────────────
create table if not exists public.tenant_features (
  id              uuid primary key default gen_random_uuid(),
  tenant_id       text not null,
  project_id      text,
  feature_key     text not null,
  enabled         boolean not null default true,
  set_by          uuid references auth.users(id),
  set_by_role     text,
  updated_at      timestamptz not null default now(),
  branding_colors jsonb,
  unique (tenant_id, project_id, feature_key)
);

-- ── drawing_change_requests ─────────────────────────────────────────────────
create table if not exists public.drawing_change_requests (
  id                 uuid primary key default gen_random_uuid(),
  project_id         text not null,
  floor_plan_id      uuid,
  change_type        text not null default 'AANPASSING'
    check (change_type in ('AANPASSING','NIEUWE_TEKENING','VERWIJDERING','PIN_WIJZIGING')),
  change_description text not null,
  requested_by       uuid references auth.users(id),
  requester_name     text,
  requested_at       timestamptz not null default now(),
  approval_token     uuid not null default gen_random_uuid() unique,
  status             text not null default 'PENDING'
    check (status in ('PENDING','APPROVED','REJECTED')),
  client_name        text,
  client_email       text,
  client_ip          text,
  approved_at        timestamptz,
  rejection_reason   text,
  legal_statement    text,
  tenant_id          text default 'demo'
);

-- ── indexen op de kerntabellen ──────────────────────────────────────────────
create index if not exists evidence_project_id_idx     on public.evidence (project_id);
create index if not exists evidence_user_id_idx        on public.evidence (user_id);
create index if not exists evidence_cloud_record_id_idx on public.evidence (cloud_record_id);
create index if not exists projects_owner_id_idx       on public.projects (owner_id);
create index if not exists projects_kwaliteitsborger_id_idx on public.projects (kwaliteitsborger_id);
