-- Wkb review-webhooks + pushregistraties
-- Doel: afgekeurde bewijsstukken automatisch doorzetten naar externe webhooks
-- en geregistreerde uitvoerders op hun toestel waarschuwen.

create table if not exists public.review_webhook_endpoints (
  id bigint generated by default as identity primary key,
  project_id text,
  target_url text not null,
  secret text,
  event_type text not null default 'EVIDENCE_REJECTED',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists review_webhook_endpoints_project_idx
  on public.review_webhook_endpoints (project_id);

create index if not exists review_webhook_endpoints_active_idx
  on public.review_webhook_endpoints (is_active);

create table if not exists public.notification_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  project_id text,
  expo_push_token text not null unique,
  platform text not null default 'unknown',
  device_label text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists notification_subscriptions_user_idx
  on public.notification_subscriptions (user_id);

create index if not exists notification_subscriptions_project_idx
  on public.notification_subscriptions (project_id);

create index if not exists notification_subscriptions_active_idx
  on public.notification_subscriptions (is_active);

alter table if exists public.review_webhook_endpoints enable row level security;
alter table if exists public.notification_subscriptions enable row level security;
