-- Server-side consumentendossier-context voor NPR 8092 en harde exportvalidatie
-- Legt projectchecklists, documentreferenties en consument-scope op bewijs vast.

do $$
begin
  if to_regclass('public.evidence') is not null then
    alter table public.evidence add column if not exists discipline_id text;
    alter table public.evidence add column if not exists dossier_scope text;
    alter table public.evidence add column if not exists stop_moment_label text;
    alter table public.evidence add column if not exists requires_measurement_tool boolean default false;

    create index if not exists evidence_project_scope_idx
      on public.evidence (project_id, dossier_scope);
  end if;
end $$;

create table if not exists public.project_checklists (
  id bigint generated by default as identity primary key,
  project_id text not null,
  checklist_type text not null,
  item_id text not null,
  title text not null,
  checked boolean not null default false,
  updated_at timestamptz not null default now(),
  user_id uuid,
  created_at timestamptz not null default now(),
  unique (project_id, checklist_type, item_id)
);

create table if not exists public.consumer_dossier_documents (
  id bigint generated by default as identity primary key,
  project_id text not null,
  document_id text not null,
  requirement_id text not null,
  title text not null,
  category text not null,
  reference_value text,
  notes text,
  updated_at timestamptz not null default now(),
  user_id uuid,
  created_at timestamptz not null default now(),
  unique (project_id, document_id)
);

create index if not exists project_checklists_project_id_idx
  on public.project_checklists (project_id);
create index if not exists project_checklists_user_id_idx
  on public.project_checklists (user_id);
create index if not exists consumer_dossier_documents_project_id_idx
  on public.consumer_dossier_documents (project_id);
create index if not exists consumer_dossier_documents_user_id_idx
  on public.consumer_dossier_documents (user_id);

alter table public.project_checklists enable row level security;
alter table public.consumer_dossier_documents enable row level security;

drop policy if exists "project_checklists_self_select" on public.project_checklists;
create policy "project_checklists_self_select"
on public.project_checklists
for select
using (auth.uid() = user_id);

drop policy if exists "project_checklists_self_insert" on public.project_checklists;
create policy "project_checklists_self_insert"
on public.project_checklists
for insert
with check (auth.uid() = user_id);

drop policy if exists "project_checklists_self_update" on public.project_checklists;
create policy "project_checklists_self_update"
on public.project_checklists
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "consumer_dossier_documents_self_select" on public.consumer_dossier_documents;
create policy "consumer_dossier_documents_self_select"
on public.consumer_dossier_documents
for select
using (auth.uid() = user_id);

drop policy if exists "consumer_dossier_documents_self_insert" on public.consumer_dossier_documents;
create policy "consumer_dossier_documents_self_insert"
on public.consumer_dossier_documents
for insert
with check (auth.uid() = user_id);

drop policy if exists "consumer_dossier_documents_self_update" on public.consumer_dossier_documents;
create policy "consumer_dossier_documents_self_update"
on public.consumer_dossier_documents
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

do $$
begin
  if to_regclass('public.projects') is not null then
    execute 'drop policy if exists "project_checklists_project_owner_select" on public.project_checklists';
    execute $policy$
      create policy "project_checklists_project_owner_select"
      on public.project_checklists
      for select
      using (
        exists (
          select 1
          from public.projects
          where public.projects.id = public.project_checklists.project_id
            and public.projects.owner_id = auth.uid()
        )
      )
    $policy$;

    execute 'drop policy if exists "project_checklists_quality_assurer_select" on public.project_checklists';
    execute $policy$
      create policy "project_checklists_quality_assurer_select"
      on public.project_checklists
      for select
      using (
        exists (
          select 1
          from public.projects
          where public.projects.id = public.project_checklists.project_id
            and public.projects.kwaliteitsborger_id = auth.uid()
        )
      )
    $policy$;

    execute 'drop policy if exists "consumer_dossier_documents_project_owner_select" on public.consumer_dossier_documents';
    execute $policy$
      create policy "consumer_dossier_documents_project_owner_select"
      on public.consumer_dossier_documents
      for select
      using (
        exists (
          select 1
          from public.projects
          where public.projects.id = public.consumer_dossier_documents.project_id
            and public.projects.owner_id = auth.uid()
        )
      )
    $policy$;

    execute 'drop policy if exists "consumer_dossier_documents_quality_assurer_select" on public.consumer_dossier_documents';
    execute $policy$
      create policy "consumer_dossier_documents_quality_assurer_select"
      on public.consumer_dossier_documents
      for select
      using (
        exists (
          select 1
          from public.projects
          where public.projects.id = public.consumer_dossier_documents.project_id
            and public.projects.kwaliteitsborger_id = auth.uid()
        )
      )
    $policy$;
  end if;
end $$;
